server:
  servlet:
    context-path: /wechat/demo
  port: 8081

wechat:
  config:
    #配置一个文字的模板ID
    singleTemplateId:
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: _cPqtgnK4qy4QuqEtfn0Iv3H5DMy55WQoN0S5oX2piQ
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
#          - oK0U562Y5ijqYRpGUtNRs0vxxxWU
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 早上好吖臭宝宝
            #你们的相遇时间
            meetDate: '2019-11-11'
            city: 呼和浩特
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            cityCode: 010000
            constellation: 双鱼座
          #把‘填写你的需要特定配置的微信用户号’覆盖位微信用户ID，可以对照正确填写好的配置示例，多用户可以按照格式继续添加下去
          填写你的需要特定配置的微信用户号:
            title: 早上好吖臭宝宝
            meetDate: '2019-11-11'
            city: 呼和浩特
            cityCode: 010000
            constellation: 双鱼座
      #颜文字模板
      emoticonsTemplate:
        templateId: _cPqtgnK4qy4QuqEtfn0Iv3H5DMy55WQoN0S5oX2piQ
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1
#发送者个人信息
personal:
  info:
    constellation: 双子座

